### ISSUE TITLE
Allow checking credentials from an action in the settings xml

### ISSUE THREAD

**Issue by michaelarnauts** [pietje666/plugin.video.vrt.nu#351] opened 2019-06-30 08:45 UTC
When configuring the addon, but you are not sure what your credentials are. The current flow is as follows:
* Go to settings and fill in your username and password.
* Save
* Open addon, go to A-Z, select a program and try to play it.
* An error occurs, start again.

We can use the `action` type in the settings xml to run an action that checks the credentials, and show a message if it failed or was successful.

I'm willing to create a PR for this, as an attempt to get to know the codebase a bit :)

**Comment by mediaminister** [comment] 2019-06-30 21:09
I can't reproduce this issue. Maybe you get an error because A-Z and sub categories listing in **the current master branch is broken** due to an issue with unicode and urllib2.quote

I fixed the broken master branch, but my pull request is not yet merged: https://github.com/pietje666/plugin.video.vrt.nu/pull/350/files

Login errors are handled already in https://github.com/pietje666/plugin.video.vrt.nu/blob/79644c7889f3a468cba7d3e09c83d639d2c51668/resources/lib/tokenresolver.py#L237

**Comment by dagwieers** [comment] 2019-06-30 21:10
I am going to merge your PR now, thanks for bringing quote_plus() to the foreground :-)

**Comment by michaelarnauts** [comment] 2019-06-30 22:35
Sure, errors are handled fine. It's just there is no way to check your credentials at the place where you fill them in. When you are not sure about your password, you need quite some clicking around to give it a few tries.

**Comment by dagwieers** [comment] 2019-06-30 22:55
@michaelarnauts I agree. But we are about to release v2.0.0 and I don't want to spend more time testing your implementation for this release.

**Closed** 2019-07-03 11:44 UTC
Labels: enhancement
