### ISSUE TITLE
Error watching content on 1.9.0

### ISSUE THREAD

**Issue by wimpunk** [pietje666/plugin.video.vrt.nu#247] opened 2019-05-17 08:32 UTC
Hi,

Yesterday we tried to watch some content using the updated plugin on the raspberry pi 3 running kodi but none of the non-live content wanted to start.  This is what I found in the kodi.log:
```
2019-05-16 21:20:39.249 T:1556370288  NOTICE: [plugin.video.vrt.nu] Got cached token
2019-05-16 21:20:39.544 T:1556370288  NOTICE: Previous line repeats 1 times.
2019-05-16 21:20:39.544 T:1556370288  NOTICE: [plugin.video.vrt.nu] protocol: mpeg_dash
2019-05-16 21:20:39.679 T:1936914832  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.vrt.nu/?publication_id=pbs-pub-7887e639-2cdb-4653-8d4d-7e2b17afbd3b&action=play&video_id=vid-127305b3-81a2-46d
2019-05-16 21:20:39.680 T:1436537712  NOTICE: Creating InputStream
2019-05-16 21:20:39.680 T:1436537712   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2019-05-16 21:20:39.681 T:1436537712   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vrt.nu/?publication_id=pbs-pub-7887e639-2cdb-4653-8d4d-7e2b17afbd3b&action=play&video_
2019-05-16 21:20:39.681 T:1436537712  NOTICE: CVideoPlayer::OnExit()
2019-05-16 21:20:39.901 T:1936914832  NOTICE: CVideoPlayer::CloseFile()
2019-05-16 21:20:39.901 T:1936914832  NOTICE: VideoPlayer: waiting for threads to exit
2019-05-16 21:20:39.901 T:1936914832  NOTICE: VideoPlayer: finished waiting
2019-05-16 21:20:54.353 T:1639994224  NOTICE: [plugin.video.vrt.nu] Got cached token
2019-05-16 21:20:54.666 T:1639994224  NOTICE: Previous line repeats 1 times.
2019-05-16 21:20:54.666 T:1639994224  NOTICE: [plugin.video.vrt.nu] protocol: mpeg_dash
2019-05-16 21:20:54.805 T:1936914832  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.vrt.nu/?publication_id=pbs-pub-7887e639-2cdb-4653-8d4d-7e2b17afbd3b&action=play&video_id=vid-127305b3-81a2-46d
2019-05-16 21:20:54.806 T:1428145008  NOTICE: Creating InputStream
2019-05-16 21:20:54.807 T:1428145008   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
2019-05-16 21:20:54.808 T:1428145008   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.vrt.nu/?publication_id=pbs-pub-7887e639-2cdb-4653-8d4d-7e2b17afbd3b&action=play&video_
2019-05-16 21:20:54.808 T:1428145008  NOTICE: CVideoPlayer::OnExit()
2019-05-16 21:20:55.038 T:1936914832  NOTICE: CVideoPlayer::CloseFile()
2019-05-16 21:20:55.039 T:1936914832  NOTICE: VideoPlayer: waiting for threads to exit
2019-05-16 21:20:55.039 T:1936914832  NOTICE: VideoPlayer: finished waiting
```
Watching live streams worked as expected.

**Comment by dagwieers** [comment] 2019-05-17 10:53
@wimpunk This appears to be an **inputstream.adaptive** issue.

- Can you give us details about your environment? Kodi version, platform, etc.
- Did everything work with a previous version of the addon ? e.g. v1.8.0 or v1.7.1 ?
- Can you still reproduce it ? Did it ever work with v1.9.0 ?

Once we have this information collected, it would be nice to know if the latest master branch is affected by this issue on your current environment. You can find instructions on how to install the latest master branch in the Wiki: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Updating#running-the-latest-development-branch-master-branch

**Comment by mediaminister** [comment] 2019-05-17 11:52
It should work fine on Libreelec 8.2.5 and Inputstream Adaptive 2.0.20.0 and higher versions.
Just make sure you rebooted Libreelec or hit **Update**  in Inputstream Adaptive information window after installing Inputstream Adaptive:

Go to **Add-ons > My Add-ons > Videoplayer Inputstream > Inputstream Adaptive** and click **Update**

If it fails again, please provide more info.

**Comment by dagwieers** [comment] 2019-05-17 13:53
@mediaminister What was the reason we didn't add a more strict dependency to **inputstream.adaptive** in addon.xml ?

**Comment by mediaminister** [comment] 2019-05-17 22:03
Compatibility with older Kodi versions and platforms. VRT offers HLS streams that work directly in Kodi player, so that gives us the opportunity to make the add-on work on a wide range of devices.

**Comment by dagwieers** [comment] 2019-05-17 22:21
Maybe we should add it *with* a version, but set as optional.

**Comment by mediaminister** [comment] 2019-05-18 07:49
Maybe, I should investigate because I don't know which impact earlier Inputstream Adaptive versions have on subtitling, audio and video playback. That's why we use HLS streams as a fallback mechanism. Disabling Inputstream Adaptive is also a valid option to fix this issue.

**Comment by dagwieers** [comment] 2019-05-18 10:01
I would like to have this in the Troubleshooting tab. An option to disable **inputstream.adaptive** for out addon, however I don't know what parts are affected by this correctly. Can you add this ?

**Comment by mediaminister** [comment] 2019-05-18 12:23
Done: https://github.com/pietje666/plugin.video.vrt.nu/pull/255

**Comment by wimpunk** [comment] 2019-05-20 09:37
Sorry for the delay @dagwieers but here are may answers

> * Can you give us details about your environment? Kodi version, platform, etc.

NAME="LibreELEC"
VERSION="9.0.1"
ID="libreelec"
VERSION_ID="9.0"
PRETTY_NAME="LibreELEC (official): 9.0.1"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="1bf54d978e8da7576ba5f83640883ecac62508d1"
OPENELEC_ARCH="RPi2.arm"
LIBREELEC_ARCH="RPi2.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="RPi"
LIBREELEC_DEVICE="RPi2"

# /usr/lib/kodi/kodi.bin  --version
18.1 Git:newclock5_18.1-Leia Media Center Kodi
Copyright (C) 2005-2018 Team Kodi - http://kodi.tv

> * Did everything work with a previous version of the addon ? e.g. v1.8.0 or v1.7.1 ?

Yes it did. I've been running both versions without any problem.

> * Can you still reproduce it ? Did it ever work with v1.9.0 ?

Yesterday I tried to watch `bumba` and the stream didn't wanted to start although it worked while using my chromecast.

**Comment by herrJones** [comment] 2019-05-20 18:45
Hello,

I cannot play any content with plugin version 1.9.0.
The GUI just restarts.

18.2 Git:20190422-f2643566d0 Media Center Kodi
Copyright (C) 2005-2018 Team Kodi - http://kodi.tv

```
Starting Kodi (18.2 Git:20190422-f2643566d0). Platform: Linux x86 64-bit
Using Release Kodi x64 build
Kodi compiled 2019-04-25 by GCC 7.3.0 for Linux x86 64-bit version 4.13.0 (265472)
Running on Gentoo/Linux 0.0, kernel: Linux x86 64-bit version 4.14.83-gentoo
FFmpeg version/source: 4.1
Host CPU: AMD A6-6400K APU with Radeon(tm) HD Graphics, 2 cores available
...
ADDON: inputstream.adaptive v2.3.17 installed
ADDON: inputstream.rtmp v2.0.4 installed
...
ADDON: plugin.video.vrt.nu v1.9.0 installed
```

... but I don't see anything in the logs when I try to start a stream...

Regards,

   Jan

**Comment by dagwieers** [comment] 2019-05-20 19:05
@wimpunk I was using LibreELEC 9.0.1 on Raspberry Pi (2 and 3) when I was developing 1.9.0 so it definitely should work. Unfortunately, I don't have enough information to deduce from.

The only thing I can say is that for v1.10.0 we have quite a few settings that could assist you in troubleshooting the problem yourself.
- Disable the use of inputstream.adaptive (which I think is the cause)
- Increase logging verbosity
- Clear VRT tokens

Normally before trying to recover, I want to understand what is going on. But here I would suggest first to see if your **inputstream.adaptive** is up to date, and also update LibreELEC (v9.0.2 is released last week).

If that doesn't help, I would suggest removing the VRT NU plugin (and when uninstalling opt to remove everything), and then reinstall the plugin and reconfigure it.

If that doesn't work either, you may want to try out the latest master branch. But again, if we don't know what the actual cause if of your problems, none of this might help.

PS The obvious things to check is your Kodi proxy settings, DNS and network settings, etc. But I assume your device is working fine for other plugins and *only* the VRT NU plugin is having issues ?

**Comment by dagwieers** [comment] 2019-05-20 19:10
Also we replaced the **requests** library with the native **urllib2** library. I wouldn't expect this to be an issue (especially since we're using the exact same environment) but maybe if you're using a proxy or VPN-type thing this may behave differently ? Since you did not fill in the template, I don't know if this is the case.

**Comment by mediaminister** [comment] 2019-05-21 16:08
I can't reproduce this bug. I did the following test scenario:
- Installed LibreELEC-Generic.x86_64-9.0.1 in VMWare Workstation Player
- Disable automatic add-on updates in Kodi
- Installed VRT Nu add-on v1.8.0
- Played some livestreams and on demand streams after providing credentials
- Changed settings: DRM, Subtitles, etc..
- Installed Inputstream Adaptive and Widevine
- Rebooted
- Played some streams: live and on demand
- Updated to VRT NU add-on v1.9.0
- Played some other streams: live and on demand

Everything worked fine. 

I suggest that anyone who has problems playing VOD streams uninstall the add-on and removes the related user data.

Uninstalling InputStream Adaptive and reinstalling can also help.

**Comment by wimpunk** [comment] 2019-05-21 19:04
Good news: the issue seems to be fixed after rebooting my system. Everything seems to work fine now.

**Comment by mediaminister** [comment] 2019-05-21 19:24
Thanks for reporting.
Seems like you got hit by a Kodi bug that was fixed a couple of months ago: https://github.com/xbmc/xbmc/pull/15780

This bug is fixed in LibreELEC 9.0.2 (Kodi 18.2)

**Comment by mediaminister** [comment] 2019-05-21 19:26
@herrJones Please open a separate bug report for your issue if it isn't fixed after rebooting Kodi.

**Comment by dagwieers** [comment] 2019-05-21 20:17
I guess we can close this issue. Thanks everyone, it's nice to get closure on issues.

**Closed by dagwieers** 2019-05-21 20:17 UTC
Labels: bug, kodi, question
