### ISSUE TITLE
livestream hangs 

### ISSUE THREAD

**Issue by goosst** [pietje666/plugin.video.vrt.nu#383] opened 2019-07-13 19:55 UTC
### Describe the bug ###
1. use livestream (een, canvas)
2. "buffer event" happens (circular icon going to 100%)
3. in majority of the cases the video hangs after 100% level is reached, the audio continues for a while before it hangs completely
4. only way to fix this somewhat reliably is reboot kodi/libreelec

This does not seem to happen in programs being replayed from the vrt archive.

### To Reproduce ###
Steps to reproduce the behavior: not sure how to trigger such a buffer event

### Expected behavior ###
Livestream should continue when 100% is reached, not hang. 

### Additional context ###

- Operating system: libreelec on tinkerboard
- Kodi version: 18.3
- Addon version: 2.0.0
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below


```

**Comment by mediaminister** [comment] 2019-07-13 20:59
I don't have a tinkerboard to test . So, please provide a debug log if possible: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Troubleshooting#log-level

You can try the following to use an alternative stream with less impact on hardware:
- Disable Widevine DRM setting
- Decrease maximal bandwith below 4096 kbps

Please report if the alternative stream works okay.

**Comment by dagwieers** [comment] 2019-07-13 21:23
Can you still log on to the LibreELEC system using SSH?
Is the system itself still responsive on the network?

LibreELEC with 18.3 is the 9.2 alpha release AFAIK, you may want to try using LibreELEC 9.0.2 instead and see if it happens there as well?

**Comment by goosst** [comment] 2019-07-14 15:04
Hello

Thanks for the quick feedback, I've enabled the detailed logging and uploaded the file when a stall of the stream happened:
[kodi.log](https://github.com/pietje666/plugin.video.vrt.nu/files/3390054/kodi.log)

> Can you still log on to the LibreELEC system using SSH?
> Is the system itself still responsive on the network?

The system and ssh keep working

> LibreELEC with 18.3 is the 9.2 alpha release AFAIK, you may want to try using LibreELEC 9.0.2 instead and see if it happens there as well?

I was using the stable version before and had the same issues, that's why I've tried to upgrade to the latest and greatest to see if it would have an effect (which it doesn't seem to have).

>     Disable Widevine DRM setting
>     Decrease maximal bandwith below 4096 kbps

I have not tried this yet but will give it a try one of the coming days.

thanks

**Comment by dagwieers** [comment] 2019-07-18 14:05
I see a lot of audio sync issues just before the live stream is eventually stalling.

So it might as well be bandwidth related, lowering it to 512kbps to see if it still happens, and then increasing it in steps to 1024 kbps and 1536 kbps would be useful to verify if this is in fact the case.
https://github.com/pietje666/plugin.video.vrt.nu/wiki/Bandwidth

**Comment by dagwieers** [comment] 2019-07-26 10:14
> I have not tried this yet but will give it a try one of the coming days.

Anything to report back?

**Comment by goosst** [comment] 2019-07-26 17:52
Changing the bandwidth didn't improve the behaviour.
Apparantly Widevine was never enabled in the first place (when I've tried to install it, it failed somewhere in Kodi).

**Comment by dagwieers** [comment] 2019-08-16 11:06
@goosst What happens when you use another add-on for streaming, like Retrospect?

IMO this is either a network-related, hardware-related or potentially a Kodi-related issue, rather than one specific to the add-on. And if we cannot reproduce this ourselves, we are unable to look for workarounds or fix it.

Yesterday, I had frequent buffering issues on a poor WIFI network, and limiting bandwidth helped in getting a lower quality stream and resolving my issue. Hopefully one day **inputstream.adaptive** is able to adapt to bandwidth as it is supposed to do.

**Comment by dagwieers** [comment] 2019-09-05 10:18
We are now 6 weeks into this issue since the last update.
I would like to know where we stand.
Is this still an issue, and have you tried with other add-ons?

**Comment by goosst** [comment] 2019-09-05 19:31
Sorry, I haven't watched a lot of live television lately and was on vacation. The two times I streamed through retrospect I didn't have issues, but that can barely count as a representative number. But with some upcoming rain and colder weather, I'll keep you updated :).

**Comment by dagwieers** [comment] 2019-09-19 02:20
Feel free to report back or reopen this issue, when you experience these problems again.

**Closed by dagwieers** 2019-09-19 02:20 UTC
Labels: bug
