### ISSUE TITLE
Crash after launch when using nakamori repo

### ISSUE THREAD

**Issue by Undeadhunter** [pietje666/plugin.video.vrt.nu#664] opened 2020-01-04 09:03 UTC
### Describe the bug ###

When opening the plugin it crashes right away

### To Reproduce ###
Open Plugin 

### Expected behavior ###

Main menu appears

### Additional context ###

- Operating system: Ubuntu 18 LTS
- Kodi version: 18.5
- Addon version: 2.3.0
- Using a VPN: no
- Country you are using the addon from: Belgium

### Log (if available) ###
```paste below
2020-01-04 09:57:51.453 T:139870114645760   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/
2020-01-04 09:57:51.457 T:139871220858176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/) failed
2020-01-04 10:00:16.358 T:139870684141312  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
2020-01-04 10:00:19.060 T:139870148216576  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/
2020-01-04 10:00:19.110 T:139870148216576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Plugin' object has no attribute 'path'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 298, in run
                                                plugin.run(argv)
                                              File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 175, in run
                                                self._dispatch(path)
                                              File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 134, in _dispatch
                                                view_func()
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 23, in main_menu
                                                VRTPlayer().show_main_menu()
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 78, in show_main_menu
                                                show_listing(main_items, cache=False)  # No category
                                              File "/home/kodi/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 129, in show_listing
                                                set_property('container.url', 'plugin://' + addon_id() + plugin.path)
                                            AttributeError: 'Plugin' object has no attribute 'path'
                                            -->End of Python script error report<--
2020-01-04 10:00:19.177 T:139869753845504   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/
2020-01-04 10:00:19.194 T:139871220858176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/) failed


```

**Comment by dagwieers** [comment] 2020-01-04 10:45
The cause for this problem appears to be an older **script.module.routing** add-on. For some reason you do not have the latest version (v0.2.3) installed. Even though it is a dependency for the VRT NU add-on.

Maybe your Linux has a different version installed using pip that is being used instead? I can tell from PyPI that it appears there is another package called **routing** that could interfere with proper operation.

**Comment by dagwieers** [comment] 2020-01-04 10:54
BTW there is a known issue in Kodi where it doesn't pick up newly installed libraries, maybe this also affects updated libraries. Restarting Kodi or rebooting the system usually fixes this issue?

**Comment by Undeadhunter** [comment] 2020-01-04 15:56
Manually updated script.module.routing and it fixed the issue. 

Strange it didn't update by itself.

**Comment by dagwieers** [comment] 2020-01-04 19:02
Thanks for reporting back !

Manually installed add-ons tend to have auto-update disabled in Kodi (not sure if this is still the case). This might be the cause. But it is weird still that our add-on installed/updated successfully while it depends on **script.module.routing v0.2.3**.

**Comment by Undeadhunter** [comment] 2020-01-08 06:47
Righto, update on the issue. Module Routing 0.2.4 breaks VRT.Nu addon. As soon as it updates to 0.2.4 it will start causing issues, downgrade to 0.2.3 => Works!

**Comment by dagwieers** [comment] 2020-01-08 07:49
There is no **script.module.routing v0.2.4**. The latest version is v0.2.3.

**Comment by Undeadhunter** [comment] 2020-01-08 08:11
Strange! Looking where it's coming from since I get an update notice for the addon...

**Comment by dagwieers** [comment] 2020-01-08 13:56
They probably had an issue with v0.2.3 and re-released v0.2.2 (without path support) as v0.2.4 for their own purpose. Best way to make a bad situation blow up later...

Can you send me the name/source of the add-on repository? You can do this by e-mail or via our facebook page if you like. I tried looking for such a release but Google was of no help.

Thanks for reporting back !

**Comment by Undeadhunter** [comment] 2020-01-08 14:21
https://github.com/bigretromike/kodi-plugin-routing

**Comment by dagwieers** [comment] 2020-01-08 14:35
I started a conversation here: https://github.com/bigretromike/kodi-plugin-routing/commit/c76ea4bf7732d57c4b6377128b60d48df00303c1#comments

@bigretromike is a very active kodi developer who has helped us in the past with our add-on. so this is good news.

**Comment by dagwieers** [comment] 2020-01-08 23:34
I am going to reopen until this is fixed.

**Comment by da3dsoul** [comment] 2020-01-10 07:15
My bad. That's an issue with two things that I wasn't aware of.
1. if `path` is not defined, it usually follows a system `path`, breaking lots of things.
2. Python inheritance is a bitch. The long version is that to reference `path` of a parent when an object is extended requires more effort than any sane language.

**Comment by dagwieers** [comment] 2020-01-10 14:21
> I thought I did things in such a way that it wouldn't break anything

No worries, but releasing a newer version for an existing add-on is akin to break at some point (say, upstream release v0.3.0 without your needed changes), and it makes support problematic (i.e. when upstream also releases a v0.2.4 version).

**Comment by dagwieers** [comment] 2020-01-12 01:09
@da3dsoul @bigretromike I haven't seen any updates yet. What is holding up a new fixed release?

**Comment by da3dsoul** [comment] 2020-01-12 03:46
Working on it. I think I've almost got it. It's also only been 2 days (since I heard about it) on an issue that's likely been around for a good year now.

**Comment by dagwieers** [comment] 2020-01-12 09:47
> It's also only been 2 days (since I heard about it) on an issue that's likely been around for a good year now.

The issue was introduced when we released a new version of VRT NU last week that uses this new path functionality. The new version was developed for 4 months, but none of the testers were using the nakamori repo. Some of our users do.
https://shokunin.monogatari.pl/repo/script.module.routing/

**Comment by da3dsoul** [comment] 2020-01-12 09:53
I see. I was wondering why I didn't hear about it until now. I have a user testing for me, as I know nothing about this add-on. I think I fixed it. I'll release when I have a verification that it works.

**Comment by da3dsoul** [comment] 2020-01-13 21:37
Okay should be good now

**Comment by bigretromike** [comment] 2020-01-14 06:07
@Undeadhunter could you please check with latest routing-forked version, that is 0.2.4.2 from nakamori repo?

**Comment by da3dsoul** [comment] 2020-01-14 07:46
He already did. I've been in contact

**Comment by bigretromike** [comment] 2020-01-14 09:43
repository is updated. @Undeadhunter said he will check later but its same version that was provided and tested before so this shouldn't be an issue anymore

**Comment by dagwieers** [comment] 2020-01-14 16:13
I will wait for feedback from @Undeadhunter before closing this issue.
Thanks everyone! :1st_place_medal:

**Comment by dagwieers** [comment] 2020-01-17 17:07
@Undeadhunter Can you confirm this is now fixed?

**Comment by Undeadhunter** [comment] 2020-01-18 07:11
Confirmed working, was too busy till this morning

**Closed** 2020-01-18 09:04 UTC
Labels: bug, reported, routing
