### ISSUE TITLE
InvalidURL due to [ symbol in URL

### ISSUE THREAD

**Issue by rfaelens** [pietje666/plugin.video.vrt.nu#148] opened 2019-04-26 19:31 UTC
### Describe the bug ###
Browsing A-Z categories does not work and results in an error message. The kodi.log mentions the following:
```
2019-04-26 18:27:04.432 T:139769946289920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 58, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 37, in router
                                                vrt_player.show_tvshow_menu_items('az')
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 56, in show_tvshow_menu_items
                                                tvshow_items = self._api_helper.get_tvshow_items(path)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py", line 31, in get_tvshow_items
                                                tvshows = requests.get(api_url, proxies=self._proxies).json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 381, in prepare_url
                                                raise InvalidURL(*e.args)
                                            InvalidURL: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE
                                            -->End of Python script error report<--
2019-04-26 18:27:04.487 T:139770969708288   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingaztvshows
2019-04-26 18:27:04.488 T:139771134720128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingaztvshows) failed

```

The URLLIB3 module included in `script.module.requests v2.21.0` cannot handle the `[` character in the URL. This can be shown by executing a simple python file:
```
import sys
sys.path.append('/storage/.kodi/addons/script.module.urllib3/lib/')
from urllib3.util import parse_url

parse_url("https://www.google.be")

myUrl = "https://vrtnu-api.vrt.be/suggest?facets%5BtranscodingStatus%5D=AVAILABLE"
parse_url(myUrl)

myUrl = "https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE"
parse_url(myUrl)
```

```
tv:~/.kodi # python ~/test.py
Traceback (most recent call last):
  File "/storage/test.py", line 11, in <module>
    parse_url(myUrl)
  File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/url.py", line 212, in parse_url
    six.raise_from(LocationParseError(url), None)
  File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/packages/six.py", line 718, in raise_from
    raise value
urllib3.exceptions.LocationParseError: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE
```

### Solution ###
I managed to get vrt.nu working by simply replacing the `[` and `]` in `vrtapihelper.py` by `%5B` and `%5D`.

### Additional context ###
```
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: Starting Kodi (18.1 Git:18.1-Leia). Platform: Linux x86 64-bit
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: Using Release Kodi x64 build
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: Kodi compiled 2019-02-21 by GCC 8.2.0 for Linux x86 64-bit version 4.19.23 (267031)
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: Running on LibreELEC (official): 9.0.1, kernel: Linux x86 64-bit version 4.19.23
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: FFmpeg version/source: 4.0.3-Kodi
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: Host CPU: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz, 4 cores available
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi/
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://envhome/ is mapped to: /storage
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://home/ is mapped to: /storage/.kodi
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: special://logpath/ is mapped to: /storage/.kodi/temp
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
2019-04-26 18:24:22.110 T:139771134720128  NOTICE: Local hostname: tv
2
2019-04-26 18:24:22.140 T:139771134720128  NOTICE: Running database version Addons27
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: audioencoder.kodi.builtin.aac v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: audioencoder.kodi.builtin.wma v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: driver.dvb.crazycat v9.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: driver.dvb.digital_devices v9.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: driver.dvb.dvb-latest v9.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: game.controller.default v1.0.8 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: game.controller.snes v1.0.8 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.global.audioengine v1.0.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.global.filesystem v1.0.2 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.global.general v1.0.3 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.global.gui v5.12.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.global.main v1.0.14 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.global.network v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.audiodecoder v2.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.audioencoder v2.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.game v1.1.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.imagedecoder v2.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.peripheral v1.3.7 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.pvr v5.10.3 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.screensaver v2.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.vfs v2.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.videocodec v1.0.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.binary.instance.visualization v2.0.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: kodi.resource v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.album.universal v3.1.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.artists.universal v4.3.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.common.allmusic.com v3.2.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.common.fanart.tv v3.6.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.common.imdb.com v3.1.4 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.common.musicbrainz.org v2.2.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.common.theaudiodb.com v2.0.2 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.common.themoviedb.org v3.1.9 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.local v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.themoviedb.org v5.1.7 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: metadata.tvshows.themoviedb.org v3.1.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: os.libreelec.tv v9.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: os.openelec.tv v9.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: peripheral.joystick v1.4.7 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: plugin.video.vrt.nu v1.7.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: plugin.video.youtube v6.4.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: repository.kodi.game v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: repository.libreelec.tv v9.0.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: repository.xbmc.org v3.1.5 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: resource.images.weathericons.default v1.1.8 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: resource.language.en_gb v2.0.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: resource.uisounds.kodi v1.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: screensaver.xbmc.builtin.black v1.0.32 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: screensaver.xbmc.builtin.dim v1.0.53 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.beautifulsoup4 v4.5.3 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.certifi v2019.3.9 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.chardet v3.0.4 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.idna v2.8 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.inputstreamhelper v0.3.4 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.kodi-six v0.0.3 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.pil v1.1.7 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.pycryptodome v3.4.3 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.requests v2.21.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.six v1.11.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.module.urllib3 v1.25.1 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: script.program.driverselect v0.1.6 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: service.libreelec.settings v9.0.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: service.subtitles.opensubtitles v5.0.16 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: service.subtitles.subscene v1.7.2 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: skin.estuary v2.0.21 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: webinterface.default v18.x-2.4.6 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.addon v18.1.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.core v0.1.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.gui v5.14.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.json v10.1.2 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.python v2.26.0 installed
2019-04-26 18:24:22.170 T:139771134720128  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
2019-04-26 18:27:04.432 T:139769946289920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 58, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/addon.py", line 37, in router
                                                vrt_player.show_tvshow_menu_items('az')
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py", line 56, in show_tvshow_menu_items
                                                tvshow_items = self._api_helper.get_tvshow_items(path)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py", line 31, in get_tvshow_items
                                                tvshows = requests.get(api_url, proxies=self._proxies).json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 381, in prepare_url
                                                raise InvalidURL(*e.args)
                                            InvalidURL: Failed to parse: https://vrtnu-api.vrt.be/suggest?facets[transcodingStatus]=AVAILABLE
                                            -->End of Python script error report<--
2019-04-26 18:27:04.487 T:139770969708288   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/?action=listingaztvshows
2019-04-26 18:27:04.488 T:139771134720128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/?action=listingaztvshows) failed
```

**Comment by JeanPoll** [comment] 2019-04-26 19:57
Can you paste your vrtapihelper.py with the fix please

**Comment by dagwieers** [comment] 2019-04-26 20:23
I experienced the same problem this evening, and will release a new version ASAP.

**Comment by dagwieers** [comment] 2019-04-26 20:27
This is a duplicate of #146

**Closed by dagwieers** 2019-04-26 20:27 UTC
Labels: bug

**Comment by dagwieers** [comment] 2019-04-26 20:47
You can get the quickfix from the master branch by following these instructions: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Updating#running-the-latest-development-tree-master-branch

PS And enjoy the new integrated TV guide, feedback welcome.

**Comment by dagwieers** [comment] 2019-04-26 23:02
We just release v1.8.0 which will become available as soon as it is accepted upstream.
You can download it using these instructions: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Updating#manual-updating

PS And enjoy the new integrated TV guide, feedback welcome.

**Comment by dagwieers** [comment] 2019-05-01 01:38
The upstream bug in urllib3 is also fixed in the meantime: https://github.com/Freso/script.module.urllib3/issues/2
