### ISSUE TITLE
Other season listing quirks

### ISSUE THREAD

**Issue by dagwieers** [pietje666/plugin.video.vrt.nu#126] opened 2019-04-08 12:54 UTC
### Describe the bug ###
We probably don't want to fix any or all of these, but I just wanted to list them here:
- Season listings are not sorted correctly
   - ~Season listing of "Winteruur" shows Season 1, 2, 4 and then 3~ #125
- Season episodes do not always show correctly
  - Episode listing of "Winteruur" for Season 1, 2 and 3 show the same broadcast date
    - Not sure if we have to add the date, now that it is being shown as metadata ?
    - Also not sure if the order makes any sense for these listings either...
  - Episode listing of "Wereldbeeld" for Season 2017 show duplicate episodes (14, 16)
    - Likely an issue at VRT
- The program "Thomas speelt het hard" has an Episode 0 which seems similar to Episode 6
    - Likely an issue at VRT
- ~Episode listing of program "Mag ik u kussen" Season 4 is empty~
- Season listings do not show the program title, which may be confusing
- Episode listing do not show the program-title nor the season
- Also wonder if it would not be better to add Season and Episode in the name
  - So instead of "01/04 - Foo bar" would "S02E03 - Foo bar" not be better ?
    (Only if we find sensible season/episode information)
  - And list all episodes together, rather than have sub-listings per season
    (Would be faster for users)

**Comment by mediaminister** [comment] 2019-04-09 17:42
1) Season sorting is fixed in https://github.com/pietje666/plugin.video.vrt.nu/pull/125
2) Episode titles:
- I think we have to implement different episode 'title types' based on api keys like `displayOptions` or `programType` which has 5 possible values: `reeksaflopend, daily, reeksoplopend, oneoff`. For instance, for daily programs like "Het Journaal" we don't need the S02E03 prefix, but a shortDate prefix is more logical.
- We need to workaround VRT Api oddities: sometimes `episodeNumber` 0 is used. For example, Thomas speelt het hard: there are 6 'regular' episodes, but VRT added a live captation of the concert and this has episode number 0.
- We have to take into account the length of the episode titles, we can only add short prefixes
3) Episode listing of program "Mag ik u kussen" Season 4 is empty: I can't reproduce this bug. For me this works perfectly.
4) Adding program name to season title: okay for me
5) Showing seasons or not: we definitely need to show a season menu when the episode list gets too long. VRT api has a setting: `displayOptions.showSeason`, so we can rely on that.

**Comment by dagwieers** [comment] 2019-04-09 18:00
Just noticed that currently there are only a few Nachtwacht episodes per season as they appear to have been cherry-picked (S01E11, S01E12, S02E11, S02E12, S03E11, S03E12). In this case an overview with S0XE0Y would probably be better too.
https://vrtnu-api.vrt.be/search?i=video&size=150&facets%5BprogramName%5D=nachtwacht

**Comment by dagwieers** [comment] 2019-04-09 18:19
It would also be nice if e.g. movies could be shown independently (so without an actual sub-folder).

**Comment by dagwieers** [comment] 2019-04-16 10:39
For the season-listing, I noticed that e.g. for Winteruur they are sorted in reverse (Season 4, Season 3, Season 2 and Season 1), but e.g. for Wereldbeeld they are sorted forward (Season 2017, Season 2018).

**Comment by dagwieers** [comment] 2019-04-16 22:11
@mediaminister I understand, still it is odd.

**Comment by dagwieers** [comment] 2019-04-17 22:57
Noticed today that *Down the road* for *Season 1* has its episodes mangled (because they were released all at once, the default order seems random). It also does not help that the season/episode information is hidden from the user.

*Would be nice if this information would be displayed as metadata on the main view below! Personally I don't like the default Kodi skin in many aspects, could be a lot better.*

**Closed** 2019-04-23 23:56 UTC
Labels: bug
