### ISSUE TITLE
RFI - How do you guys debug Kodi add-ons? 

### ISSUE THREAD

**Issue by piejanssens** [pietje666/plugin.video.vrt.nu#582] opened 2019-11-19 19:23 UTC
Sorry for this to be so off topic. I hope you don't mind.

I'm trying to contribute some enhancements to the yelo kodi add-on and need a good way to debug the add-on (introducing async HTTP requests to speed up loading). 

I like working with VS Code and so I tried - but failed - to get PTVSD working with Kodi.
See https://forum.kodi.tv/showthread.php?tid=349345

I would like to know what IDE you guys are using and how you are debugging.

@dagwieers @michaelarnauts @pietje666 @mediaminister

**Comment by dagwieers** [comment] 2019-11-19 19:34
I am doing everything in VIM, pretty old-school.

We wrote our own Kodi stub libraries for testing, and I use it for development and troubleshooting as well as it does not require a real Kodi for testing our code (for everything but playing the actual streams). But next to automated testing (using Travis) we do heavily test it on different versions of Kodi (@mediaminister is the man).

**Comment by mediaminister** [comment] 2019-11-19 20:38
> I would like to know what IDE you guys are using and how you are debugging.

I use Linux Mint's default text editor xed and Mate terminal.

I directly test and debug new code in Kodi on Linux:
- I symlink my local add-on git repositories to the Kodi installation directory:
```ln -s ~/plugin.video.vrt.nu/ ~/.kodi/addons/```
- Open debug log in xed:
```xed ~/.kodi/temp/kodi.log```
- Open Kodi from terminal:
```kodi```

Before a new release I test the add-on in different virtual machines:
- Two Virtualbox VM's: Windows 10 and PrimeOS (Android x64) 
The Windows 10 VM has a user with special chars in its name to test unicode support. I both test Kodi 18.4(Python 2) and Kodi 19 nightly(Python 3).
- Different [LibreELEC versions](http://ftp.belnet.be/mirror/libreelec.tv/) (ova images) in VMWare Workstation 15 Player

**Comment by michaelarnauts** [comment] 2019-11-19 21:04
I'm using pycharm. The community version is free and works really nice.

**Comment by pietje666** [comment] 2019-11-19 21:51
Having developped the addon from the start i started out with pycharm. I did not like it that much and since i was used to using visual studio at work i switched to visual studio. 

For the testing part i challenged the same difficulties as you did in the beginning the addon was tightely coupled to Kodi dependencies. And i performed testing by putting log statements and running the application manually. Since i did not like this approach, I moved all Kodi dependend stuff to a single class which allowed me to mock the kodi part out so i was able to create some unit tests. This greatly improved testing.

**Comment by piejanssens** [comment] 2019-11-19 22:20
Thank you all for the quick responses. Seems you have a pretty slick CI setup. It surprises me that no one is using remote debugging, which IMO works easier/faster than a sort of trial and error approach based on the debug logs.

There are solutions for VS, VS Code, PyCharm and Eclipse which allow you to insert a breakpoint in you code and then attach your debugger (e.g. VS Code built in debugger) to it and let you do all sorts of debugging goodness: step through the code, print/watch/modify variables, ...

**Comment by pietje666** [comment] 2019-11-20 20:25
> Thank you all for the quick responses. Seems you have a pretty slick CI setup. It surprises me that no one is using remote debugging, which IMO works easier/faster than a sort of trial and error approach based on the debug logs.
> 
> There are solutions for VS, VS Code, PyCharm and Eclipse which allow you to insert a breakpoint in you code and then attach your debugger (e.g. VS Code built in debugger) to it and let you do all sorts of debugging goodness: step through the code, print/watch/modify variables, ...

We do debugging running the unit tests, i say unit tests but actually they are more integration tests. Hence we do "**all sorts of debugging goodness: step through the code, print/watch/modify variables, ...**"
It is also easy for new people to run the tests and debug through them since it are things supported from the IDE out of the box.

**Comment by dagwieers** [comment] 2019-12-01 01:42
With the recent performance regression, let me add that we use cProfile from time to time to ensure our code is performing as expected. Either locally (using the stubs) or on a real Kodi system. This helps to get performance information, but also number of calls per function or accumulated time spent. See #169 and #606

**Comment by dagwieers** [comment] 2019-12-01 01:43
I am going to close this issue, but feel free to add or discuss here when see fit.

**Closed by dagwieers** 2019-12-01 01:43 UTC
Labels: question, testing
